---
version: "3"
services:
  frontend_server:
    build: ./frontend
    expose:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
  backend_server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FIBER_REACT_DEV_MODE=true
      - FIBER_REACT_FRONTEND_SERVER=http://frontend_server:5173
